### ISSUE TITLE
recursive key search only goes down 3 levels

### ISSUE THREAD

**Issue by leedium** [any-code/riot-i18n#1]
trying to do a localise, is there a limit to how many items can be nested?

```
i18n.localise("create.labels.test")  works
i18n.localise("create.labels.chat.test")  doesn't work

//i18n.localise("create.labels.test") - > "au revoir"  working
{
  "en":{
    "create":{
      "labels": {
          "test":"au revoir"
        "chat:":{ 
        }       
      }
    }
  }
}

//i18n.localise("create.labels.chat.test") - > "create.labels.chat.test"  not working
{
  "en":{
    "create":{
      "labels": {
        "chat:":{
          "test":"au revoir"
        }       
      }
    }
  }
}

```

**Comment by qrb** [comment]
Hey @leedium you have a typo in your key `chat:` 
this works:
testable.localise("create.labels.chat:.test") => "au revoir"

**Comment by leedium** [comment]
Ok, now that was embarrassing.  I knew it had to be me!
Wonderful. I think I'm going to start taking breaks between marathon coding session!

Thanks qrb. I was going to stick with your lib regardless. Great work!

Cheers!

**Comment by qrb** [comment]
Cool!
